spring.application.name=student_tracker

server.port:7070

spring.datasource.url:jdbc:mariadb://localhost:3306/student_tracker
spring.datasource.username:springstudent
spring.datasource.password:springstudent

# turn off the spring boot banner
spring.main.banner-mode=off

# reducing logging level to warn and error
logging.level.root=warn

# logs to display SQL statements
logging.level.org.hibernate.SQL=debug
# logs to display the values in SQL statements
logging.level.org.hibernate.orm.jdbc.bind=trace

# Configuration to auto-create tables
spring.jpa.hibernate.ddl-auto=update

